---
settings:
  name: ONTAP tools for VMware vSphere 10.0
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '10.0'
    url: "/ontap-tools-vmware-vsphere-100"
  - version-number: '10.3'
    url: "/ontap-tools-vmware-vsphere-10"
  - version-number: '10.2'
    url: "/ontap-tools-vmware-vsphere-102"
  - version-number: '10.1'
    url: "/ontap-tools-vmware-vsphere-101"
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation relative aux outils ONTAP pour VMware vSphere 10.0
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: manage
  - section: migrate
  - title: Mentions légales
    url: "/legal-notices.html"
