---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Les outils ONTAP prennent en charge une configuration haute disponibilité \(HA\) afin d"assurer la continuité des outils ONTAP en cas de panne.' 
---
= Configuration de la haute disponibilité des outils ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les outils ONTAP prennent en charge une configuration haute disponibilité afin d'assurer la continuité des outils ONTAP en cas de défaillance.

Les outils ONTAP s'appuient sur la fonction haute disponibilité de VMware vSphere et sur la fonction tolérance aux pannes (FT) de vSphere pour assurer une haute disponibilité. La solution haute disponibilité permet une reprise rapide en cas de panne provoquée par :

* Défaillance d'hôte
+

NOTE: Seule la défaillance d'un nœud est prise en charge.

* Défaillance du réseau
* Défaillance de machine virtuelle (défaillance du système d'exploitation invité)
* Panne de l'application (outils ONTAP)


Aucune configuration supplémentaire n'est requise pour que les outils ONTAP assurent la haute disponibilité. Seuls les hôtes vCenter Server et ESXi doivent être configurés à l'aide de la fonction HA de VMware vSphere ou de la fonction FT de vSphere en fonction de leurs besoins. La haute disponibilité et la tolérance de défaillance nécessitent des hôtes en cluster associés au stockage partagé. FT a des exigences et des limites supplémentaires.

Outre la solution haute disponibilité VMware vSphere et la solution FT vSphere, les outils ONTAP permettent également de garantir le fonctionnement continu des services des outils ONTAP.


NOTE: VCenter HA n'est pas pris en charge par les outils ONTAP.
