---
permalink: concepts/concept_configure_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser VASA Provider pour ONTAP pour créer et gérer des volumes virtuels VMware \(vVvols\). Vous pouvez provisionner, modifier, monter et supprimer un datastore vvols. Vous pouvez également ajouter du stockage au datastore vVols ou supprimer le stockage du datastore vVols pour plus de flexibilité.' 
---
= Configurations de VASA Provider pour vvols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser VASA Provider pour ONTAP pour créer et gérer des volumes virtuels VMware (vvols). Vous pouvez provisionner, modifier, monter et supprimer un datastore vvols. Vous pouvez également ajouter du stockage au datastore vVols ou supprimer le stockage du datastore vVols pour plus de flexibilité.

Un datastore vVols se compose d'un ou plusieurs volumes FlexVol au sein d'un conteneur de stockage (également appelé stockage de support). Une machine virtuelle peut être répartie entre un datastore vvols ou plusieurs datastores vvols.

Alors que vous pouvez créer un datastore vVols ayant plusieurs volumes FlexVol, tous les volumes FlexVol au sein du conteneur de stockage doivent utiliser le même protocole (NFS ou iSCSI) et les mêmes serveurs virtuels de stockage (SVM).


NOTE: Il est recommandé d'inclure plusieurs volumes FlexVol dans un datastore vvols pour davantage de performances et de flexibilité. Les volumes FlexVol étant soumis à des restrictions de nombre de LUN qui limitent le nombre de machines virtuelles, y compris plusieurs volumes FlexVol, vous pouvez stocker davantage de machines virtuelles dans votre datastore vVvols. L'ajout de volumes divers augmente les fonctionnalités du datastore. Il peut s'agir d'un mélange de volumes fins et épais, de sorte que les deux types de machines virtuelles puissent être créés sur le datastore.

VASA Provider crée différents types de vVols lors du provisionnement de machines virtuelles ou de la création de VMDK.

* *Config*
+
VMware vSphere utilise ce datastore vvols pour stocker des informations de configuration.

+
Dans les implémentations SAN (bloc), le stockage correspond à une LUN de 4 Go.
VCenter 8 utilise la capacité de 256 Go de LUN en provisionnement fin.

+
Dans une implémentation NFS, il s'agit d'un répertoire contenant les fichiers de configuration de VM tels que le fichier vmx et les pointeurs vers d'autres datastores vVvols.

* *Données*
+
Ce vVvols contient des informations sur le système d'exploitation et des fichiers utilisateur.

+
Dans les implémentations SAN, il s'agit d'une LUN de la taille du disque virtuel.

+
Dans une implémentation NFS, il s'agit d'un fichier de la taille du disque virtuel.

* *Permuter*
+
Ce vvols est créé lorsque la machine virtuelle est mise sous tension et est supprimé lors de la mise hors tension de la machine virtuelle.

+
Dans les implémentations SAN, il s'agit d'une LUN de la taille de la mémoire virtuelle.

+
Dans une implémentation NFS, il s'agit d'un fichier de la taille de la mémoire virtuelle.

* *Mémoire*
+
Ce vVvols est créé si l'option snapshots de mémoire est sélectionnée lors de la création de snapshots de VM.

+
Dans les implémentations SAN, il s'agit d'une LUN de la taille de la mémoire virtuelle.

+
Dans une implémentation NFS, il s'agit d'un fichier de la taille de la mémoire virtuelle.


