---
permalink: configure/create_vvols_datastore.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez créer un datastore vVols avec de nouveaux volumes ou avec des volumes existants. Vous pouvez également créer un datastore vVols en combinant des volumes existants et de nouveaux volumes. 
---
= Créer un datastore vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un datastore vVols avec de nouveaux volumes ou avec des volumes existants. Vous pouvez également créer un datastore vVols en combinant des volumes existants et de nouveaux volumes.


NOTE: Cette option permet de vérifier que les agrégats racine ne sont pas mappés sur un SVM.

Vous devez transmettre x-auth pour l'API. Vous pouvez générer cette x-auth à partir de la nouvelle API ajoutée sous Auth dans swagger.

[listing]
----
/virtualization/api/v1/auth/vcenter-login
----
. Créez un datastore vVols avec un nouveau volume.
Get Aggregate ID, Storage_ID(SVM UUID) using ONTAP REST API.
+
[listing]
----
POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
----
+
Utilisez l'URI suivant pour vérifier l'état :

+
[listing]
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Corps de demande pour le datastore NFS

+
[listing]
----
{
   "name":"nfsds1",
   "protocol":"nfs",
   "platform_type":"aff",
   "moref":"domain-c8",
   "volumes":[
      {
         "is_existing":false,
         "name":"vol_nfs_pvt",
         "size_in_mb":2048000,
         "space_efficiency":"thin",
         "aggregate":{
            "id":"d7078b3c-3827-4ac9-9273-0a32909455c2"
         },
         "qos":{
            "min_iops":200,
            "max_iops":5000
         }
      }
   ],
   "storage_backend":{
      "storage_id":"654c67bc-0f75-11ee-8a8c-00a09860a3ff"
   }
}
----
+
Corps de la demande pour le datastore iSCSI :



[listing]
----
{
   "name" : "iscsi_custom",
   "protocol" : "iscsi",
   "platform_type": "aff",
   "moref" : "domain-c8",
   "volumes" : [
       {
           "is_existing" : false,
           "name" : "iscsi_custom",
           "size_in_mb" : 8034,
           "space_efficiency" : "thin",
           "aggregate" : {
               "id" : "54fe5dd4-e461-49c8-bb2d-6d62c5d75af2"
           }
       }
   ],
   "custom_igroup_name": "igroup1",
   "storage_backend": {
                       "storage_id": "eb9d33ab-1960-11ee-9506-00a0985c6d9b"    }
}
----
. Créez un datastore vVols avec des volumes existants.
+
Obtenez Aggregate_ID et volume_ID à l'aide de l'API REST ONTAP.

+
[listing]
----
     POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
----
+
Corps de la demande



[listing]
----
     {
    "name" : "nfsds2",
    "protocol" : "nfs",
    "platform_type": "aff",
    "moref" : "domain-c8",
    "volumes" : [
        {
              "is_existing": true,
              "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
            }
    ],
    "storage_backend": {
                        "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }

}
----