---
permalink: manage/update_vcenter_ontap_credentials.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez mettre à jour les informations d"identification vCenter et ONTAP à l"aide de la console de maintenance.' 
---
= Mettez à jour les informations d'identification vCenter et ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour les informations d'identification vCenter et ONTAP à l'aide de la console de maintenance.

*Ce dont vous aurez besoin*

Vous devez disposer des informations de connexion utilisateur maint.

*À propos de cette tâche*

Si vous avez modifié les informations d'identification de vCenter, ONTAP ou Datalif après le déploiement, vous devez mettre à jour les informations d'identification à l'aide de cette procédure.

*Étapes*

. Depuis vCenter Server, ouvrez une console vers VASA Provider.
. Connectez-vous en tant qu'utilisateur de maintenance.
. Entrez `4` Pour sélectionner support et Diagnostics.
. Entrez `1` Pour sélectionner accès au shell de diagnostic.
. Entrez `y` pour continuer.
. Mettez à jour les informations d'identification si nécessaire :
+
.. Pour mettre à jour les informations d'identification ONTAP, lancer la commande :
+
--
otv-update --ontapUserName <new username> --ontapPassword <new password>

--
.. Pour mettre à jour les informations d'identification vCenter, exécutez la commande :
+
--
otv-update --vcenterUsername <new username> --vcenterPassword <new password>

--
.. Pour mettre à jour le datalif, exécutez la commande :
+
--
otv-update --dataLif <New Datalif IP>

--



